# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts
trigger:
  branches:
    include:
    - 'main'
  paths:
      include:
      - /project_3/*
      
  
stages:
- stage: 'Main_CI_project_3'
  displayName: 'FrontEnd Main CI'
  jobs:
    - template: '.templates/azure-pipelines-CI.yaml'