# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- 'master'


stages:
- stage: 'BuildDeploy'
  displayName: 'Build & deploy'
  jobs:     
  - job:
    displayName: 'Npm install & build'      
    pool:
      vmImage: 'ubuntu-18.04'              
    steps:
      - task: Npm@1
        displayName: 'npm Install' 
        inputs:
          command: install
          workingDir: '$(Build.SourcesDirectory)'
      - task: CopyFiles@2
        inputs:
          Contents: '**'
          TargetFolder: 