# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- 'master'


variables:
- name: workingDirectory
  value: '$(Build.SourcesDirectory)'
- name: vmImage
  value: 'ubuntu-18.04'
- name: buildContext
  value: '.'
- name: npm_config_cache
  value: $(Pipeline.Workspace)/.npm
- name: CYPRESS_CACHE_FOLDER # Overrides the default cache location
  value: $(Pipeline.Workspace)/.cache/Cypress
- name: buildOutputFolder # Overrides the default cache location
  value: build
- group: shopping-frontend-dev

stages:
- stage: 'BuildDeploy'
  displayName: 'Build & deploy'
  jobs:     
  - job:
    displayName: 'Npm install & build'      
    pool:
      vmImage: '${{ variables.vmImage }}'              
    steps:
      - task: Npm@1
        displayName: 'npm Install' 
        inputs:
          command: install
          workingDir: '${{ variables.workingDirectory }}'
