trigger:
  branches:
    include:
    - 'dev'
  paths:
    include:
    - project_1/*

stages:
- stage: 'Dev_CI project_1'
  displayName: 'FrontEnd Dev CI'
  jobs:
    - template: '.templates/azure-pipelines-CI.yaml'
