# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts
trigger:
  branches:
    include:
    - 'dev'
  paths:
      include:
      - /project_2/*

stages:
- stage: 'Dev_CI_project_2'
  displayName: 'FrontEnd Dev CI'
  jobs:
    - template: '.templates/azure-pipelines-CI.yaml'
